### ISSUE TITLE
麦克风问题

### ISSUE THREAD

**Issue by Dreamail** [NiceYume/Clover-ASUS_TUF_B450M_PLUS_GAMING#1]
麦克风有声音吗
我折腾了好久
麦克风前置后置都没有声音

**Comment by woshinibaba6666** [comment]
麦克风没试过。可以试试换Apple alc的layout id。目前现在建议折腾opencore。貌似amd内核的clover补丁不更新了。只能支持到10.15.1
---原始邮件---
发件人:"Pai2Chen"<notifications@github.com>
发送时间:2020年2月18日 星期二 下午8:11
收件人:"NiceYume/Clover-ASUS_TUF_B450M_PLUS_GAMING"<Clover-ASUS_TUF_B450M_PLUS_GAMING@noreply.github.com>
抄送:"Subscribed"<subscribed@noreply.github.com>
主题:[NiceYume/Clover-ASUS_TUF_B450M_PLUS_GAMING] 麦克风问题 (#1)

麦克风有声音吗
我折腾了好久
麦克风前置后置都没有声音

&mdash;

**Comment by Dreamail** [comment]
已经换oc了，AppleALC死活不行
现改用VoodooHDA
